### ISSUE TITLE
readme.md:52: Add http://i.jpeek.org badge after...

### ISSUE THREAD

**Issue by 0pdd** [dgroup/docker-unittests#19]
The puzzle `14-4e641228` (from #14) in [`readme.md`](https://github.com/dgroup/docker-unittests/blob/959e6e8ff6629d394ab8f4d36a7048077725eda1/readme.md#L52-L52) has to be resolved: "Add http://i.jpeek.org badge after release to maven central"

https://github.com/dgroup/docker-unittests/blob/959e6e8ff6629d394ab8f4d36a7048077725eda1/readme.md#L52-L52

The puzzle was created by dubinka on 11-Dec-17. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by dgroup** [comment]
https://github.com/yegor256/jpeek/issues/230

**Comment by 0pdd** [comment]
The puzzle `14-4e641228` has disappeared from the source code, that's why I closed this issue.

**Comment by dgroup** [comment]
jpeek isn't a service, that's a self-hosted solution.
