### ISSUE TITLE
New screenshots are required for v1.1.x (including example of xml report)

### ISSUE THREAD

**Issue by dgroup** [dgroup/docker-unittests#204]

**Comment by bodax** [comment]
docker-unittests-1.0.3.jar dosen't run, it caused by "no main manifest attribute"

**Comment by dgroup** [comment]
@bodax, try to build project using `run.sh` in the project.
https://github.com/dgroup/docker-unittests/blob/master/run.sh
The script will build the JAR file and run it with `docs/image-tests.yml`.

**Comment by dgroup** [comment]
@bodax, add `-o xml` option
`java -jar app.jar -i <docker-image> -f <yml-file> -o xml`.

Also, please add this information to the `readme.md`

**Comment by bodax** [comment]
@bodax Ok, will check it soon.
