### ISSUE TITLE
Update copyright to 2019

### ISSUE THREAD

**Issue by dgroup** [dgroup/docker-unittests#214]

**Comment by dgroup** [comment]
@bodax, yes, of course.
1. Change the year in `license.txt`
2. IDEA > Settings > Editor > Copyright > Copyright Profiles > find your current profile
3. Change the `2017-2018` to `2017-2019`, press [Apply], [OK]
4. Chose root directory in the `Project View` (Alt+1), right mouse click, press [Upgrade Copyright] and chose root folder
5. Press [OK]

All files within the root directory should be changed.

**Comment by bodax** [comment]
@dgroup I did all these steps, but didn't find option how to change it in all files
