### ISSUE TITLE
No install/download section

### ISSUE THREAD

**Issue by g4s8** [dgroup/docker-unittests#241]
I tried to download it from maven central and run using commands:
```bash
mvn dependency:get \ 
  -DgroupId=com.github.dgroup \
  -DartifactId=docker-unittests \
  -Dversion=1.1.0
java -jar ~/.m2/repository/com/github/dgroup/docker-unittests/1.1.0/docker-unittests-1.1.0.jar \
  -f tests.yml \
  -i alpine:latest
```
but got an error:
```
no main manifest attribute, in /home/g4s8/.m2/repository/com/github/dgroup/docker-unittests/1.1.0/docker-unittests-1.1.0.jar
```
then I tried to download sources from this repo build it and run:
```bash
git clone  --depth=1 https://github.com/dgroup/docker-unittests.git
cd docker-unittests
mvn clean install
cd ..
java -jar ./docker-unittests-1.1.0/target/docker-unittests-1.1.0.jar \
  -f tests.yml \
  -i alpine:latest
```
and got same error (`no main manifest attribute`).

Honestly speaking, I just forgot how to run it and now I can't find any documentation about it. Also it would be great if I'll be able to download a `jar` from somewhere (e.g. Github releases) without complex commands.

**Comment by dgroup** [comment]
Hi @g4s8 ,
Thank you for the issue reporting, will add the documentation.

As W/A the `jar` is available as `shaded` release
https://github.com/dgroup/docker-unittests/releases/download/v1.1.0/docker-unittests-app-1.1.0.jar

https://github.com/dgroup/docker-unittests/releases

**Comment by dgroup** [comment]
By default, there is no manifest within the *.jar for mvn central.

**Comment by g4s8** [comment]
@dgroup thanks this shaded release works fine, I tried to search this jar in latest github release https://github.com/dgroup/docker-unittests/releases/tag/1.1.0 (`1.1.0` instead of `v1.1.0`)

**Comment by dgroup** [comment]
@g4s8, i've renamed the release
![image](https://user-images.githubusercontent.com/1651114/56081672-8a662500-5e2d-11e9-92f1-8fe17733dc57.png)

The key problem here is that rultor didn't attach the files to the release
https://github.com/yegor256/rultor/issues/1160

For this purpose, the `github-release-plugin` is used, however, it also can't attach the dist to the existing repository (only create from scratch or delete+create again).
https://github.com/jutzig/github-release-plugin/
I'm wondering to raise the RR to them.

**Comment by dgroup** [comment]
@rultor release, tag=`1.1.1`

**Comment by g4s8** [comment]
@dgroup now it's clear, thanks
