### ISSUE TITLE
Docker-unittests pased the test without Internet connections

### ISSUE THREAD

**Issue by bodax** [dgroup/docker-unittests#60]
Output: ``` Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 127.0.0.53:53: server misbehaving ```

**Comment by dgroup** [comment]
Hi @bodax ,
Could you please provide TC/AR/ER for this case?

**Comment by dgroup** [comment]
Fixed in scope of #99.
