### ISSUE TITLE
Arg.java:32: Make arg with generic

### ISSUE THREAD

**Issue by 0pdd** [dgroup/docker-unittests#76]
The puzzle `78-b81b1100` from #78 has to be resolved:

https://github.com/dgroup/docker-unittests/blob/f05b4fd79b3310658d2d7efb3d1edcc5f592f217/src/main/java/org/dgroup/dockertest/cmd/Arg.java#L32-L32

The puzzle was created by dgroup on 07-Feb-18. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by dgroup** [comment]
Fixed in scope of #78 (60381a73ed8d444715edf2f47bc374140201282c)
