### ISSUE TITLE
PlainFormattedText.java:74: Avoid runtime exceptions in...

### ISSUE THREAD

**Issue by 0pdd** [dgroup/docker-unittests#84]
The puzzle `82-854bc7d4` from #82 has to be resolved:

https://github.com/dgroup/docker-unittests/blob/c5824b17de41deccc6505fcf3063bd671845ed96/src/main/java/org/dgroup/dockertest/text/PlainFormattedText.java#L74-L74

The puzzle was created by dgroup on 09-Feb-18. 

Estimate: 0 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by dgroup** [comment]
Not actual anymore.
